export const data = {
  header: [
    '',
    'Name',
    'Application',
    'Producent',
    'Code',
    'Location',
    'Units',
    'Notes',
    'To order',
  ],
  content: [
    {
      name: 'tool 1',
      application: 'milling',
      producent: 'sandvik',
      code: 'code',
      location: 'location',
      units: 3,
      notes: 'blablabla',
      id: 1,
    },
    {
      name: 'tool 2',
      application: 'milling',
      producent: 'walter',
      code: 'code',
      location: 'location',
      units: 3,
      notes: 'blablabla',
      id: 2,
    },
    {
      name: 'tool 3',
      application: 'turning',
      producent: 'sandvik',
      code: 'code',
      location: 'location',
      units: 3,
      notes: 'blablabla',
      id: 3,
    },
  ],
};
